### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by GTadim** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2021-2-e2-proj-int-t2-descarte-sustentavel#7]
Elaboração do diagrama de classes e entidades

**Comment by amandaoliveira21** [comment]
Tarefa concluída, porém o conteúdo dos microfundamentos direcionados a esta etapa foram insuficientes no sentido de base de informação, entretanto, realizamos pesquisas através de outras fontes para que fosse possível a conclusão desta tarefa.
